### ISSUE TITLE
Define code block in markdown instead of frontmatter

### ISSUE THREAD

**Issue by gragland** [uidotdev/usehooks#1]
Currently code is defined in markdown frontmatter, which requires escaping and makes it impossible to see changes in the commit diffs. Look into using `gatsby-remark-prismjs` or see how it's done on https://github.com/gaearon/overreacted.io

**Comment by gragland** [comment]
We need to think about how this would work with the new JS/TS toggle (https://github.com/gragland/usehooks/pull/89), since that relies on having two separate code values in markdown frontmatter.

**Comment by bozheville** [comment]
Hey @gragland,

I have a question, why not just using embed code editor from codesandbox?

I understand it's heavy, but the preview can be hidden under a button

**Comment by gragland** [comment]
Last time I checked the Codesandbox editor seemed to have a pretty high file size for what is needed, which was really just syntax highlighting. I think `gatsby-remark-prismjs` would probably make the most sense, which is what is used on https://github.com/gaearon/overreacted.io

**Comment by bozheville** [comment]
Looks possible. I found a way to implement it, even with switching a language. I'll create a PR later today, but changing a language may look a bit hacky.

**Comment by kevin940726** [comment]
@gragland Enjoying your work!

Slightly unrelated, but seems like the code is manually synced with CodeSandbox instance? I'm the author of [`remark-codesandbox`](https://github.com/kevin940726/remark-codesandbox). Allow me to recommend using it to automatically generate CodeSandbox instance directly from your markdown file. No more manual sync with the CodeSandbox instance, also allowing contributors to send PRs to update the snippets and automatically update the CodeSandbox instances as well.

I'd be happy to send a PR, but maybe it's best to be done after #93 landed?

**Comment by gragland** [comment]
@kevin940726 Some of the earlier posts have CodeSandbox examples that are a bit different from the markdown code. Generally it's just more HTML structure and CSS so they look nicer, which isn't needed in the markdown code example, which I try to keep as short as possible. I'll consider this for the future though if it looks like I don't have the time to put extra effort into the CodeSandbox examples. In that case it probably makes sense to just have them mirror the posts and automate with your library.

**Comment by kevin940726** [comment]
@gragland You don't have to include those HTML/CSS in the markdown code block! You can create a separate template (let it be a CodeSandbox, or a directory in the file system) and only override the file desired from the code block.
I got it though! It's not the top priority for now :). Just want to let you know there's this option available if you need it, and potentially could be useful after #93.

**Comment by gragland** [comment]
@kevin940726 Gotcha! That's good to know. Definitely something I want to revisit.
