### ISSUE TITLE
useMediaMatches

### ISSUE THREAD

**Issue by jacobrask** [uidotdev/usehooks#10]
A hook which is simlar to the useMedia hook, but uses listeners on the media query so that it can listen to any type of media change and not only screen size. 

```
import json2mq from 'json2mq';
import { useEffect, useState } from 'react';

function useMediaMatches(query, defaultMatches = false) {
  const [matches, setMatches] = useState(defaultMatches);
  const queryString = typeof query !== 'string' ? json2mq(query) : query;
  useEffect(
    () => {
      const update = event => setMatches(event.matches);
      const mediaQueryList = window.matchMedia(queryString);
      setMatches(mediaQueryList.matches);
      mediaQueryList.addListener(update);
      return () => mediaQueryList.removeListener(update);
    },
    [queryString]
  );
  return matches;
}
```

json2mq is useful if you want to write your media queries as objects, but is otherwise optional.

```
import { useEffect, useState } from 'react';

function useMediaMatches(query, defaultMatches = false) {
  const [matches, setMatches] = useState(defaultMatches);
  useEffect(
    () => {
      const update = event => setMatches(event.matches);
      const mediaQueryList = window.matchMedia(query);
      setMatches(mediaQueryList.matches);
      mediaQueryList.addListener(update);
      return () => mediaQueryList.removeListener(update);
    },
    [query]
  );
  return matches;
}
```

**Comment by gragland** [comment]
Thank you! Do you see any downsides (performance or otherwise) to this method over a listener on the resize event? At first glance your method seems all around better. If that's the case I'll just go ahead and update the original useMedia post.

Edit: Also would you mind sharing a basic usage example? I'm failing to see how this supports matching on multiple media queries (or does it)?

**Comment by gragland** [comment]
I've gone ahead and updated the origin [useMedia](https://usehooks.com/useMedia/) post. Thanks for the suggestions!
