### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [uidotdev/usehooks#102]
Save our eyes. And batteries.

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by petercr** [comment]
Hello 🙋🏻‍♂️ I would like to go ahead and tackle this issue. 
If it's up for grabs?

The website definitely has a **very** ***very white*** ⚪ background. 
But the rest of the site [code snippets] are all in a dark theme anyways. 

If I did put together a PR for this issue, would you like to have an icon/svg that users could click to change it back and forth? 
Or is this more of a just use system defaults kind of thing. 

Just let me know 👌🏻

Thanks
