### ISSUE TITLE
Move TypeScript toggle button to MDX

### ISSUE THREAD

**Issue by gragland** [uidotdev/usehooks#103]
We want the TypeScript toggle button to appear between the post description and the code example. Looks like moving it into MDX is the best way to do that.

**Comment by gragland** [comment]
@bozheville do you still have time to handle this one?

**Comment by bozheville** [comment]
@gragland I am. Sorry for the long delay, I am trying to find not too hacky implementation

**Comment by gragland** [comment]
@bozheville Cool, no worries, just wanted to make sure :)

**Comment by bozheville** [comment]
@gragland small update. It's in progress. Hope to complete it within the next week

**Comment by gragland** [comment]
@bozheville Awesome, thanks for the update!
