### ISSUE TITLE
This should be published to npm

### ISSUE THREAD

**Issue by thejspro** [uidotdev/usehooks#119]
I think this website is fantastic and I love all that you're doing @gragland.

I know this has already been requested before #49 and #64 and considering that the collection of your recipes has grown substantially it should be published to npm.

I think a lot of people right now simply copy & paste your code, possibly without even referencing the source. Publishing to npm would ensure you get credit when it's due and more importantly would make everyone life's easier.

I do understand you might not have the time to maintain the hooks that you've already published on your blog, but given the amount of stars you have I am pretty sure the community would help you moderate PRs if necessary.

I don't think you need to be involved in maintenance personally if you don't have to - just publishing the existing hooks would be a good start.

Thanks for all you're doing and let's preserve your work by making it available on npm :)

Best,
John

**Comment by abdul-hamid-achik** [comment]
i 100% agree with you, although i like to copy paste, i find myself using these hooks pretty often and i would gladly contribute to write tests for the hooks if that helps to make this a package
