### ISSUE TITLE
useMemo demo not working

### ISSUE THREAD

**Issue by TooMuchLagWillKillYou** [uidotdev/usehooks#143]
The [useMemo demo](https://codesandbox.io/s/jjxypyk86w) is currently not working, the error message is: _Could not find module in path: 'react/jsx-runtime' relative to '/src/index.js'_

Just update `react` and `react-dom` to the latest version and it will work again.

**Comment by AMDevelopOB** [comment]
Ok, I updated package.json to the latest versions.

**Comment by ghost** [comment]
Solved in https://github.com/uidotdev/usehooks/pull/150
