### ISSUE TITLE
useLockBodyScroll does not work on IOS safari

### ISSUE THREAD

**Issue by AkromDev** [uidotdev/usehooks#145]
**What is the current behavior?**
On iOS, the body is still scrollable when overlay is opened even though `useLockBodyScroll` is used. It works fine in Desktops and android phones though.

**Steps to reproduce**
- Open your IOS safari
- Go to [this live demo](https://fixed-position-ios-scroll.vercel.app/use-hooks)
- Click `Open` button to open the overlay and scroll inside that overlay to bottommost. 
- Keep scrolling after reaching overlay bottom and notice body gets scrolled as well

## I recorded the issue below.

<video src='https://user-images.githubusercontent.com/41626115/190914100-a0637e3a-d3bc-43bc-b794-975f382a34f3.MP4' width=180 type="video/mp4"></video>

Notes to take from video recording

- I opened overlay from bottommost open button. So the body conent should stay here when I come back from overlay.
- I was able to reach to the overlay bottom and click close button
- Despite body scroll lock, I was able to scroll body up after scrolling up overlay. As a result, I was seeing topmost body content instead of bottommost where I opened overlay.

**What is the expected behavior?**
Only overlay should be scrollable while body scroll should be locked just like in desktop and android browsers

**A little about versions:**  
- _OS_: IOS 15.1
- _Browser (vendor and version)_: safari 15.1
- _React_: ^18.2.0
- _`use-hooks`_:^18.2.0 

View [source code here](https://github.com/AkromDev/fixed-position-ios-scroll/blob/master/src/components/BodyLockWithUseHooks.jsx)

**Comment by jur-ng** [comment]
Why was this issue marked as completed @tylermcginnis ? As far as I know mobile safari does not do anything with `overflow` on `body`. Maybe it could be possible to work around this by for example temporarily disabling `scroll` or `touchmove` events on the body? :thinking:

**Comment by tylermcginnis** [comment]
When we pushed the re-write/library, we closed all existing issues. This was one of them.
