### ISSUE TITLE
Description and tagline for `useGeoLocation` are for `useHistoryState`

### ISSUE THREAD

**Issue by mikesprague** [uidotdev/usehooks#173]
I was taking a look at some of your hooks and noticed that some of the content for `useGeoLocation` seems to have come from the `useHistoryState` (maybe a copy/paste that didn't get updated 🤷🏼‍♂️).

The file in question is: [`./usehooks.com/src/content/hooks/useGeolocation.mdx`](https://github.com/uidotdev/usehooks/blob/main/usehooks.com/src/content/hooks/useGeolocation.mdx) (published location: https://usehooks.com/usegeolocation)

As mentioned in the issue title, as far as I can tell it's the tagline and description that are incorrect.

Thanks!

**Comment by tylermcginnis** [comment]
Oof. Thank you! We'll get that fixed.

**Comment by benadam11** [comment]
Fixed - https://github.com/uidotdev/usehooks/pull/174
