### ISSUE TITLE
[useMesure] Error in example using "useLongPress" hook in "useMeasure" page

### ISSUE THREAD

**Issue by ealch** [uidotdev/usehooks#181]
**Reproduction steps:**
1. Visit the "useMeasure" webpage at https://usehooks.com/usemeasure.
2. Scroll down to the example section
3. In the example code, observe that the example is referencing the `useLongPress` hook instead of the expected `useMeasure` hook.

![image](https://github.com/uidotdev/usehooks/assets/7937529/77e1c60e-0fb4-4133-a37a-869bfe37f24f)

**Expected behavior:** 
The example on the `useMeasure` should demonstrate the usage of the `useMeasure` hook.

**Comment by anilChouhan-sh** [comment]
Hi, I would like to contribute to this issue.

After reading the docs and the code following is my approach.

1. Get the right code(App.js) from code sandbox by using the sand box id from useMeasure.mdx file
2. Update useMeasre.mdx file with the correct code for useMeasure.

If my above approach is correct do let me know I will raise a PR.

**Comment by tylermcginnis** [comment]
Fixed in #201
