### ISSUE TITLE
No typescript declarations

### ISSUE THREAD

**Issue by sannajammeh** [uidotdev/usehooks#185]
Neither JSDoc, DT nor TS declarations are in this project making it hard to use when typescript is in the codebase. Regardless, its a great collection of hooks!

**Comment by tylermcginnis** [comment]
We're planning on adding them soon.

**Comment by jamesvclements** [comment]
In the meantime, is adding our own `use-hooks.d.ts`, something like this, the best solve?

```ts
declare module "@uidotdev/usehooks" {
  export function useMediaQuery(query: string): boolean;
  ...
}

```

**Comment by diego-musa** [comment]
@tylermcginnis, may you reopen and stay it open until it's done? I'm planning to use the lib but typing are important in my job. I'd like to stay in track of it watching this issue.
Could you do it for us?

**Comment by Zombobot1** [comment]
This should definitely be an open issue. I need to remove this library from our project right now. I want to get it back when the declarations are done.

**Comment by Kolby-Udacity** [comment]
> This should definitely be an open issue. I need to remove this library from our project right now. I want to get it back when the declarations are done.

I feel the same way. I would prefer to use this library over usehooks-ts because it offers more hooks, but I've grown addicted to code completion.

Anyone know of any better options?

edit: use https://github.com/streamich/react-use

**Comment by stefan-b314** [comment]
> > This should definitely be an open issue. I need to remove this library from our project right now. I want to get it back when the declarations are done.
> 
> I feel the same way. I would prefer to use this library over usehooks-ts because it offers more hooks, but I've grown addicted to code completion.
> 
> Anyone know of any better options?
> 
> edit: use https://github.com/streamich/react-use

Thanks @Kolby-Udacity, currently I am looking for some useMap hook. Tried react-use, but had issues here too, so I am going to try https://github.com/react-hookz/web next.

**Comment by Kolby-Udacity** [comment]
> Thanks @Kolby-Udacity, currently I am looking for some useMap hook. Tried react-use, but had issues here too, so I am going to try https://github.com/react-hookz/web next.

Oh nice, this one looks even better

**Comment by vedran-passendo** [comment]
Unfortunately since TS is required on our project, even though I loved this package I can't use it. Not sure why this got closed @tylermcginnis? (btw I love your courses 👍 )

**Comment by Waryen** [comment]
Same here, I was surprised there was not typescript support, I'll see if I can help on that on my free time

Edit: didn't saw this [PR](https://github.com/uidotdev/usehooks/pull/206)
