### ISSUE TITLE
Issue: TypeError in App.js when using custom hook useFetch

### ISSUE THREAD

**Issue by faizaniqbalLC** [uidotdev/usehooks#187]
I encountered a TypeError while using a custom hook called useFetch in the App.js file. The error message states that (0, _usehooks.useFetch) is not a function. This issue is preventing the proper functioning of my application.
Expected Behavior:
The useFetch custom hook should be a function and should not result in a TypeError.
Please let me know why this error is coming?

![image](https://github.com/uidotdev/usehooks/assets/102588816/a3d346e7-6af8-4e20-8f34-b67c79fb10c1)

**Comment by movoid12** [comment]
hey @faizaniqbalLC , weird, it works perfectly on my machine. Can show us your `package.json` file?

**Comment by faizaniqbalLC** [comment]
Hey @movoid12 , not weird brother, did you use the same hook that I'm using?

**Comment by faizaniqbalLC** [comment]
I managed to resolve the issue by using the following code snippet in my own package instead of the current versions of React and ReactDOM. In order to use 3-4 or more experimental hooks, I had to downgrade the package.json file of my project. Do you understand what I mean? I have mentioned all the package.json files below.

```
    "react": "0.0.0-experimental-bfb9cbd8c-20230223",
    "react-dom": "0.0.0-experimental-bfb9cbd8c-20230223"
```
**with experimental installation package.json file in node_modules**

![image](https://github.com/uidotdev/usehooks/assets/102588816/66aa05a5-e476-48f5-8234-9191bb41370d)

**without experimental installation package.json file in node_modules**

![image](https://github.com/uidotdev/usehooks/assets/102588816/5913ba1a-a45e-4189-9a18-9c823a5984a7)

**After downgrading my project package.json file**

![image](https://github.com/uidotdev/usehooks/assets/102588816/13b64458-61e3-46b7-81ab-03a382090683)

**Comment by tylermcginnis** [comment]
Yeah `useFetch` depends on React's experimental `useEffectEvent` hook, which requires `react-dom@experimental` and `react@experimental`.
