### ISSUE TITLE
Only compatible with React v18+

### ISSUE THREAD

**Issue by Gabrielfcs** [uidotdev/usehooks#193]
This library is using `useSyncExternalStore` which was added in React v18, so for older versions it becomes incompatible.

That said, the readme file should be updated to warn of the incompatibility.

**Comment by nsdonato** [comment]
Create a PR for this, if you think the text could be improved, let me know 😊

https://github.com/uidotdev/usehooks/pull/196

**Comment by tylermcginnis** [comment]
Thank you. We'll get the change added to the README in @nsdonato's commit.
