### ISSUE TITLE
Open source repo? 

### ISSUE THREAD

**Issue by emielvanseveren** [uidotdev/usehooks#195]
I am confused about the purpose of this repo. It gives the impression of being open source (MIT license). But its not?

**Comment by bernbecht** [comment]
+1. Trying to study the hooks' implementations but didn't find them

**Comment by CanRau** [comment]
They're in [index.js](https://github.com/uidotdev/usehooks/blob/main/index.js) though unfortunately no types ([yet](https://github.com/uidotdev/usehooks/issues/185))

**Comment by nsdonato** [comment]
@tylermcginnis this issue can be closed ✨.

**Comment by man-trackunit** [comment]
> +1. Trying to study the hooks' implementations but didn't find them

If the hook you're looking for is not in `index.js`, maybe look at the _experimental_ branch → `index.js`
