### ISSUE TITLE
useCLickAway Demo not working

### ISSUE THREAD

**Issue by hilmanski** [uidotdev/usehooks#197]
trying locally, as well as at docs
https://usehooks.com/useclickaway

didn't work with error 
/src/App.js: Could not find module in path: 'react/cjs/react-jsx-runtime.development.js' relative to '/node_modules/react/jsx-runtime.js' (3:0)

in Local: Could not find a declaration file for module '@uidotdev/usehooks for
```
import { useClickAway } from "@uidotdev/usehooks";
```

**Comment by mzavattaro** [comment]
Could be related to https://github.com/uidotdev/usehooks/issues/200
