### ISSUE TITLE
Is there a reason vscode shows this error?

### ISSUE THREAD

**Issue by georgefromohio** [uidotdev/usehooks#199]
Could not find a declaration file for module '@uidotdev/usehooks'. '.../node_modules/@uidotdev/usehooks/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/uidotdev__usehooks` if it exists or add a new declaration (.d.ts) file containing `declare module '@uidotdev/usehooks';` ts (7016)

**Comment by linsolas** [comment]
Hello @georgefromohio 

This is related to #185, the TypeScript definitions are not yet available on this project.

**Comment by georgefromohio** [comment]
Thank you! Love this package of gems!
