### ISSUE TITLE
Adding new custom hook (useForm)

### ISSUE THREAD

**Issue by abdofola** [uidotdev/usehooks#205]
Hi :wave:  @tylermcginnis,

  I'd like to __contribute__ to add the `useForm` hook !

The idea of the hook is pretty neat and simple, and serves for a wide range of usecases :
+ the `form` valiation is built on top of javascirpt `constraint validation` api.
+ give the user the ability to opt into make the component/input `controlled` if they want to render part of the `ui` based on the `state`, but by default it's `uncontrolled` to prevent unnecssary re-rendering.
+ In case any of the `form` controls/inputs is `invalid`, the user can display custom error messages if they're not happy with the built-in ones.

To demonstrate my points, the user might interact with the hook like so :

***uncontrolled component*** :
```
type FormControls = {
 email : string;
}

function Example_1() {
 const {formState, attache, onSubmit, reset} = useForm<FormControls>();
 const handleSubmit = (formdata : FormControls) => {
  console.log({formdata});
  //reset();
 };

  return (
   <form onSubmit={onSubmit(handleSubmit)}>
    {formState.errors.email && <span>{formState.errors.email}</span>}
    <label htmlFor="email">Email:</label>
    <input {...attache("email",{type: 'email',id:"email", required: true, autoFocus: true})} />
    <button type='submit'>submit</button>
   </form>
 );
}
```
***controlled component*** :
```
type FormControls = {
 firstName: string;
 lastName?: string;
}

function Example_2(props) {
 const {formState, attache, onSubmit, reset} = useForm<FormControls>({defaultValues:props.data});
 const handleSubmit = (formdata : FormControls) => {
  console.log({formdata});
  //reset();
 };

 return (
   <>
    <h1>{`Hi, ${formState.formdata.firstName} ${formState.formdata.lastName}`}</h1>
    <form onSubmit={onSubmit(handleSubmit)}>
      {formState.errors.firstName && <span>{formState.errors.firstName}</span>}
      <label htmlFor="firstname">First name:</label>
      <input {...attache("firstName",{
         type: 'text',
         id:"firstname",
         required: true,
         isControlled: true,
         errMsg: 'You need to enter your firstname'
       })}
      />
      <label htmlFor="lastname">Last name:</label>
      <input {...attache("lastName",{type: 'text',id:"firstname", isControlled: true)} />
      <button type='submit'>submit</submit>
    </form>
   </>
 );
}
```

__So, I am wondering if the idea of the hook aligns with the mission of this repo before making a `pull` request.__

**Comment by tylermcginnis** [comment]
We're trying not to add any more hooks unless we have to. I think this one is too broad for this library. I'd recommend using a more robust solution like [react hook form](https://react-hook-form.com/) or formik.
