### ISSUE TITLE
Adding useImageLoad hook

### ISSUE THREAD

**Issue by ssi02014** [uidotdev/usehooks#209]
@tylermcginnis 👋
I want to contribute to that repository, so I register an issue before I register a pull request.
The custom hook I want to add is "useImageLoad".

This hook is very neat and quite useful.

For example, you can use the return value, isLoaded, to show an alternate UI, such as a skeleton UI, before the image has finished loading.

You can also give it animation effects like opacity.

```js
const Example = () => {
  const { ref, isLoaded } = useImageLoad();

  return (
    <img
      ref={ref}
      src={imageUrl}
      width={400}
      height={400}
      style={{ opacity: isLoaded ? 1 : 0, transition: 'opacity 0.5s' }}
    />
  );
};
```

It's simple to use. Just pass "ref" to the img tag and you're done.
And the return value, isLoaded, tells you whether the image has finished loading or not.

Please review the hook for suitability for your repository, and if you find it useful enough, I'll create a pull request for it. 🙏

**Comment by tylermcginnis** [comment]
I appreciate the offer but we're trying not to add any other hooks for now.
