### ISSUE TITLE
Include hook code on website

### ISSUE THREAD

**Issue by twhitbeck** [uidotdev/usehooks#210]
I saw #49 so I guess you can't please everyone. But in the spirit of [design for copy/paste](https://twitter.com/dan_abramov/status/1659348147150245889) and the original goal of hooks, I think it'd be great for the source code of the hooks to be right on the website, rather than just a snippet to npm install them. Ideally in JS and TS.

Another suggestion, and I know this is a ton of work, but I would really love it multiple versions of hooks could be shown from simple to more complex with descriptions of the reasons for added complexity. Many times, when I've gone to copy a hook, it has included all kinds of complexity to handle cases that I simply don't care about.

Again I recognize the maintenance burden this entails, and I'm super appreciative of the work that has already gone into this collection of hooks. These are just a couple ideas I had that I think could make this stand out as the number 1 collection of react hooks out there. :man_cook: :kiss:

**Comment by amirahad** [comment]
Totally agreed with you @twhitbeck .
i would also request the team to include the source code of particular hooks right on the website.

**Comment by tylermcginnis** [comment]
This was a big debate when we decided to redo the project since, as you mentioned, it goes against the ethos of the original vision. With that said, we decided that a library was better for a variety of reasons and I don't think we're going to go back on that decision now – especially after a few months of work have been put in *not* building that vision. Sorry, I know this is the lame answer.

**Comment by JaKXz** [comment]
> This was a big debate when we decided to redo the project since, as you mentioned, it goes against the ethos of the original vision. With that said, we decided that a library was better for a variety of reasons and I don't think we're going to go back on that decision now – especially after a few months of work have been put in _not_ building that vision. 

Thanks @tylermcginnis for pointing me to this issue. Is the repo where the hooks are published from open source? That would at least be a compromise but I can't seem to find it.

**Comment by tylermcginnis** [comment]
@JaKXz Yup. They're all [here](https://github.com/uidotdev/usehooks/blob/main/index.js). We'll probably re-organize them in the future (to not be in a single file), but for now it works fine.

**Comment by GeorgeWL** [comment]
So often installing was just not needed for the smaller hooks, so it was nice back when each hook also had the code snippet so one could just copy that instead of installing a whole module.

Can you bring these back?
