### ISSUE TITLE
`useLocalStorage` produce different state for server and client rendering

### ISSUE THREAD

**Issue by moshest** [uidotdev/usehooks#219]
When using `useLocalStorage` it loads the local storage immediately if the `window` exists and fallback to the default value on server side. This produce inconsistency when rendering code in SSR as the server and client code do not match!

Instead, the first render should always be from the default value and only later when `useEffect` called it will update the state to the local storage value correctly.

The same apply for `useSessionStorage`.

**Comment by moshest** [comment]
Woops, worng repo.

**Comment by tylermcginnis** [comment]
You should switch so you don't have this problem 😉

**Comment by moshest** [comment]
I don't want to use the experimental react version, I ended up write a short implementation 🤷‍♂️

**Comment by tylermcginnis** [comment]
OK fine that's fair.
