### ISSUE TITLE
Library is making the test fail because "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by RodriCabrera** [uidotdev/usehooks#221]
Hi!

I have the following issue. When I import some of the hooks into a component, the test for that specific component fails (jest - react testing library) 

```ts
Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/rodrigocabrera/Documents/.../.../node_modules/@uidotdev/usehooks/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import * as React from "react";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      3 | import { useTranslation } from 'react-i18next';
      4 | import { useTheme } from '@emotion/react';
    > 5 | import { usePreferredLanguage } from '@uidotdev/usehooks';
        | ^
      6 |

      at Runtime.createScriptFromCode (node_modules/jest-cli/node_modules/jest-runtime/build/index.js:1496:14)
      at Object.<anonymous> (src/features/common/components/Footer/Footer.tsx:5:1)
      at Object.<anonymous> (src/features/common/components/Footer/test/Footer.test.tsx:2:1)
```

I tried adding the following to the jest.config, with no success:
```
  transformIgnorePatterns: ['node_modules/(?!@uidotdev/usehooks/*)'],
```

Thank you

**Comment by ivajo26** [comment]
I have the same problem, which is the solution? @tylermcginnis

**Comment by shaunsaker** [comment]
I managed to fix this by adding:

```
    "transformIgnorePatterns": [
      "node_modules/(?!(@uidotdev/usehooks)/)"
    ],
```

to my `jest.config`.

**Comment by NameFILIP** [comment]
if using a `create-react-app` you can do the following in your package.json:
```
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!@uidotdev/usehooks)/\"",
```

**Comment by Arunjenson** [comment]
any solutions for this?

**Comment by nicogreenarry** [comment]
I tried adding the `transformIgnorePatterns` and it didn't fix the issue for me. I see that there are [ways to enable ESM modules in Jest](https://jestjs.io/docs/ecmascript-modules), but Jest says they're experimental and has some warnings about doing so.

I ended up deciding to uninstall this library and use [usehooks-ts](https://www.npmjs.com/package/usehooks-ts) instead, which resolved the issue for me ¯\_(ツ)_/¯

**Comment by Arunjenson** [comment]
thanks mate

**Comment by lukethacoder** [comment]
Closed for no reason? [usehooks-ts](https://www.npmjs.com/package/usehooks-ts) "fixed" the issue 🤷

**Comment by xxKeefer** [comment]
yeah, guess i'll go use usehooks-ts instead?

**Comment by Tilogorn** [comment]
Any update on this? It's a serious blocker... 

- Changing the `transformIgnorePatterns` did not help.
- `usehooks-ts` is not API compatible to `@uidotdev/usehooks`.
- My project is written in JS, not TS (I know, no blocker, but still feeling weird)

I am currently mocking it out and faking return values with `jest.mock('@uidotdev/usehooks', () => ( useDebounce: jest.fn() }));` but this can't be the solution...

Not sure how I can help as I am not too deep into JEST and ESM module loading, but I can certainly provide a minimal working example of the issue.

**Comment by shlomoweb1** [comment]
It wasn't very comforting after writing a component that Jest not playing nice with it, hoping for a follow-up but switching to open source [usehooks-ts](https://www.npmjs.com/package/usehooks-ts)
