### ISSUE TITLE
ts error: Incorrect Return Type in `useCopyToClipboard` Hook

### ISSUE THREAD

**Issue by delmalih** [uidotdev/usehooks#222]
**Description**:
I've noticed an inconsistency in the return type documentation for the `useCopyToClipboard` hook. The returned type for the `copiedText` value is currently documented as:

```typescript
{
    error: Error | null;
    text: string | null;
}
```

**Expected Behavior**:
I believe there might be an error in the documentation, and the return type for `copiedText` should be `string | null` instead of `{ error: Error | null; text: string | null; }`.

**Steps to Reproduce**:
The documentation for the `useCopyToClipboard` hook states that the `copiedText` value should have the type mentioned above.

**Actual Behavior**:
The current documentation might be incorrect regarding the type of the `copiedText` value.

**Proposed Solution**:
I suggest updating the documentation to reflect the correct return type for the `copiedText` value in the useCopyToClipboard hook, changing it to `string | null`.
This change would help prevent confusion for developers using the hook and ensure accurate and clear documentation.

Thank you for maintaining this useful repository! 🙌

**Comment by tylermcginnis** [comment]
Fixed. Thank you!
