### ISSUE TITLE
usePrevious hook

### ISSUE THREAD

**Issue by noshower** [uidotdev/usehooks#224]
why not use useRef hook? I think, use useRef hook can reduce the number of renderings

```
export function usePrevious(value) {
  const currentRef = React.useRef();
  const previousRef = React.useRef();

  if (value !== currentRef.current) {
    currentRef.current = value;
    previousRef.current = currentRef.current;
  }

  return previousRef.current;
}
```

**Comment by tylermcginnis** [comment]
Because you're not supposed to read or write to refs during rendering.

<img width="1351" alt="Screenshot 2023-09-01 at 8 51 30 AM" src="https://github.com/uidotdev/usehooks/assets/2933430/6f5018c0-c37d-4dae-b4f2-75de31ece903">

**Comment by noshower** [comment]
thanks
