### ISSUE TITLE
useHistoryState clear function error

### ISSUE THREAD

**Issue by tomekxoxo** [uidotdev/usehooks#236]
I imported hook into Provider file and when I invoke clear function i get Error `initialState is not defined`
![Screenshot 2023-09-19 at 15 12 12](https://github.com/uidotdev/usehooks/assets/45947389/73d922ec-c1dd-40c5-b4b5-af6e90846f36)

**Comment by tylermcginnis** [comment]
Fixed. We'll get a release out soon. Thank you.
