### ISSUE TITLE
Error: useLocalStorage is a client-only hook

### ISSUE THREAD

**Issue by sadaffathali** [uidotdev/usehooks#238]
I use useLocalStorage in a next-hook, I'll use that hook in the client-side component and still get this error 

`Error: useLocalStorage is a client-only hook`

this is the hook I wrote: 

`export default function useUserToken(): UseUserTokenHook {
    const [userToken, setUserToken] = useLocalStorage(USER_TOKEN_KEY)

    useEffect(() => {
        if (typeof window === 'undefined') {
            return
        }
    }, [])

    const setToken = (token?: string) => {
        setUserToken(token)
    }

    if (!userToken) {
        const randomToken = crypto.randomUUID()
        setToken(randomToken)
    }

    return [userToken as string, setToken]
}`

**Comment by graup** [comment]
This is a duplicate of https://github.com/uidotdev/usehooks/issues/218

That said, I also ran into this, and I think it is not very intuitive. Maybe it can be improved on this usehooks side.

**Comment by tylermcginnis** [comment]
I'll (soon) update the descriptions of all the client-only hooks to clarify the problem/solution.

**Comment by gardner** [comment]
If you found this looking for an answer, you can use this component:

`ClientOnly.tsx`

```typescript
"use client";
/**
 * Hack to work around next.js hydration
 * @see https://github.com/uidotdev/usehooks/issues/218
 */
import React from 'react';
import { useIsClient } from "@uidotdev/usehooks"

type ClientOnlyProps = {
  children: React.ReactNode;
};

export const ClientOnly: React.FC<ClientOnlyProps> = ({ children }) => {
  const isClient = useIsClient();

  // Render children if on client side, otherwise return null
  return isClient ? <>{children}</> : null;
};
```

Then wrap your client components:

```tsx
<ClientOnly>
  <MyComponentThatUsesHooks />
</ClientOnly>
```

**Comment by silouanwright** [comment]
@tylermcginnis why can't `isClient` be incorporated internally into each of these hooks? Also, could we reconsider just keeping these issues open until after this is fixed and / or addressed?
