### ISSUE TITLE
useBrowserHistory

### ISSUE THREAD

**Issue by zcallan** [uidotdev/usehooks#24]
Hey! I just created a new hook which makes use of the browser history state, hope you find this one interesting.

It's main goal is for inside projects that have modals / popups / dialogs, they can easily be hooked into the browser's native history, so they can be closed (and optionally reopened) when the user presses back (or forward) in their browser.

It's a common UX bug I see in many, many websites so I hope this hook can help developers easily fix this issue.

It's especially bad on Android phones when modals don't use the browser history to create a new entry for itself, I find myself losing the page I was on all the time!

Anyway, hope you like this one! Thanks.

https://github.com/zcallan/use-browser-history

```jsx
import React, { useState } from 'react'

import useBrowserHistory from 'use-browser-history'

function Modal({ isOpen, onClose, onOpen }) {
  const [handleBack] = useBrowserHistory( 'my-modal', isOpen, onClose, onOpen );

  if ( !isOpen )
    return null;

  return (
    <div className="modal">
      <div className="modal-backdrop" onClick={handleBack} />

      <div className="modal-box">
        <p>Hello!</p>
        <button onClick={handleBack}>Close modal</button>
      </div>
    </div>
  )
}

function App() {
  const [isOpen, setIsOpen] = useState( false );

  return (
    <div>
      <button onClick={() => setIsOpen( true )}>Open modal</button>

      <Modal
        isOpen={isOpen}
        onClose={() => setIsOpen( false )}
        onOpen={() => setIsOpen( true )}
      />
    </div>
  );
}
```

**Comment by gragland** [comment]
Nice! For these cases I tend to push a new url to history and have url params as props that control the modal (using next.js). That way you kind of get this functionality for free. That said, not everyone may be using a framework that makes that easy to do and a simple hook that adds that is pretty cool.
