### ISSUE TITLE
Extend useMeasure to other attributes

### ISSUE THREAD

**Issue by tansanDOTeth** [uidotdev/usehooks#242]
https://github.com/uidotdev/usehooks/blob/546df269e31a9ba10e0f6902fbda66d5eab7caa7/index.js#L743C20-L747

The current implementation only returns the width and height, but there is quite a lot more information that would be helpful in many circumstances: https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly

**Comment by tylermcginnis** [comment]
Not a bad idea, but I don't want to change the return value right now. Will consider this in the future. Thank you!
