### ISSUE TITLE
Show source code for hooks?

### ISSUE THREAD

**Issue by JaKXz** [uidotdev/usehooks#243]
Hi! I am a big fan of usehooks and something I used a lot previously as a teaching/learning tool was being able to see the source code for the hooks. Is that possible with the new design? It looks great but does lose some magic without the source code. 

Thanks!

**Comment by tylermcginnis** [comment]
Duplicate of #210

**Comment by JaKXz** [comment]
Sorry I missed this in my search.

**Comment by tylermcginnis** [comment]
No worries!
