### ISSUE TITLE
Search and Discovery

### ISSUE THREAD

**Issue by khill-fbmc** [uidotdev/usehooks#245]
Before I begin my "issue" I want to thank you all for making this library and site available for free for everyone. These are very handy hooks!

OK, so my issue is with the website. I was looking around to see what you offer, and I have to admit, it is difficult.

Why is there no search? If I think you might offer a hook, why do I have to scroll the list and grok a card layout? Can there be table or list layout too? 

That is all, thanks for listening :)

**Comment by tylermcginnis** [comment]
Thank you!

And yeah we're aware of it. We're planning on adding better search functionality in the future but are busy with some other stuff right now.

**Comment by khill-fbmc** [comment]
I hope "other stuff" is more fun hooks 😃
