### ISSUE TITLE
React 17 as peer dependency ?

### ISSUE THREAD

**Issue by ritz078** [uidotdev/usehooks#248]
Is it possible to allow react 17 as a peerdependency for this project ? I really don't want to override peer deps specifically for this package and not sure if React 17 will work.

**Comment by tylermcginnis** [comment]
It won't, unfortunately. The library uses `useSyncExternalStore` in a bunch of places which was released in React v18.

**Comment by ritz078** [comment]
That makes sense. Thank you for your quick response.
