### ISSUE TITLE
Type 'MutableRefObject<Element>' is not assignable to type 'LegacyRef<HTMLDialogElement> | undefined'.

### ISSUE THREAD

**Issue by V-iktor** [uidotdev/usehooks#250]
This example is not working in Typescript 5 with React 18

https://usehooks.com/useclickaway

**Comment by kttmv** [comment]
I was able to solve this issue by explicitly specifying the type of `useClickAway` like this:
```typescript
const ref = useClickAway<HTMLDialogElement>(() => {
    ...
})
```
The same goes for other elements as well. If you want to reference, for example, a `div`, you should specify `<HTMLDivElement>`
