### ISSUE TITLE
useScript should return loaded when script is already in the page

### ISSUE THREAD

**Issue by jfnault-seedbox** [uidotdev/usehooks#251]
In my scenario, the initial execution of 'useScript' functions correctly. 
However, if I navigate away from the page and return to it. because the script is already loaded, the onload wont fire and the script will remain in loading state forever

**Comment by jfnault-seedbox** [comment]
I've submitted a pull request to address this issue. 
First attemps: You can view it [here](https://github.com/uidotdev/usehooks/pull/252/files/ced82a7ecc0b727a93c357d58f9332773d27758c).

_After reflection, I see an issue with this logic. It will end up returning 'ready' for a script that was returning an error the first time. For this feature, I think we will need module-scoped variables. I'll create another PR._

**Comment by jfnault-seedbox** [comment]
Updated version [here](https://github.com/uidotdev/usehooks/pull/252/files).

**Comment by tylermcginnis** [comment]
Fixed [here](https://github.com/uidotdev/usehooks/commit/9f27cc6ec6bcfc84a6794beefa029e3efaa608dd). We'll get a new release out soon.

**Comment by jfnault-seedbox** [comment]
Thank @tylermcginnis Ill test it today!

**Comment by jfnault-seedbox** [comment]
Tested it, work well on my side

**Comment by tylermcginnis** [comment]
Shipped. https://github.com/uidotdev/usehooks/commit/fa7f8bf3983cad6358c27e1a0547799b0865a168
