### ISSUE TITLE
Error: useLocalStorage is a client-only hook - thrown from a client component

### ISSUE THREAD

**Issue by mmkal** [uidotdev/usehooks#254]
Hi - this library looks very useful! I'm trying to use `useLocalStorage` with nextjs (app directory). It's functional when running `next dev`, but breaks with `next build`.

Repro on StackBlitz: https://stackblitz.com/edit/vercel-next-js-h3p4a9?file=app%2Fclient-component.tsx

The failure is:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: useLocalStorage is a client-only hook
    at getLocalStorageServerSnapshot (/home/projects/vercel-next-js-h3p4a9/.next/server/chunks/206.js:7247:9)
    ... more stack frames
```

This is in a client component, here's the implementation from the repro:

```tsx
'use client';
import { useLocalStorage } from '@uidotdev/usehooks';

export const ClientComponent = () => {
  const [value, setValue] = useLocalStorage('someKey', 'x');

  return (
    <>
      <input onChange={(ev) => setValue(ev.target.value)} value={value} />
      <div>The value is: {value}</div>
    </>
  );
};
```

I haven't been able to find any workaround for this other than patching node_modules (to not throw and return `initialValue` from the hook when `typeof window === 'undefined`. But without that it's just unusable in nextjs app directory as far as I can tell.

**Comment by tylermcginnis** [comment]
Believe it or not, "use client" doesn't mean it only runs on the client 🙃

This should point you in the right direction - https://github.com/uidotdev/usehooks/issues/218

**Comment by mmkal** [comment]
Thanks, missed all those other issues. Good to know there's a workaround. 

Still, seems like a usability problem. I know client components also have an SSR pass, but the important thing is they _will_ run in the client, so shouldn't it be fine to return the initial value when pre-rendering?

**Comment by tylermcginnis** [comment]
No, because if the value in localStorage when React hydrates is different than the default value you established on the server, you'll get a [client/server mismatch error](https://nextjs.org/docs/messages/react-hydration-error).

**Comment by mmkal** [comment]
I see. I guess I'd assumed that an additional render would take care of that on the client side. I just read through the [`useSyncExternalStore` docs](https://react.dev/reference/react/useSyncExternalStore) and it says re `getServerSnapshot`:

> If you omit this argument, rendering the component on the server will throw an error

So maybe this library doesn't need to explicitly throw anyway? Is there any way you can think of that would allow for developers to have a server-default behaviour without wrapping the whole component (e.g. if you do `useLocalStorage('k', 'v', { ssr: true })` then it always uses `initialValue` on first render, then updates in the next render)? Maybe this library could bake in any or all of the three suggestions on the page you linked? https://nextjs.org/docs/messages/react-hydration-error, or maybe a suspense/error boundary that can catch the prerender error and show a fallback UI, higher up in the tree?

**Comment by tylermcginnis** [comment]
It doesn't need to throw an error, but (IRRC) the one we throw is more descriptive than the one React does. I think the solution is to make the docs more clear that it should be used together with `useIsClient` when you're working in a Next app. Been meaning to do that but haven't yet. Don't love the idea of trying to get around hydration errors.

**Comment by billsbooth** [comment]
> make the docs more clear that it should be used together with useIsClient when you're working in a Next app.

How would you define component state from useIsClient? Might as well just read local storage directly and populate default react state.

**Comment by tylermcginnis** [comment]
@billsbooth https://github.com/uidotdev/usehooks/issues/218#issuecomment-1835624086

**Comment by gpoole** [comment]
@tylermcginnis your [comment about client-server mismatches](https://github.com/uidotdev/usehooks/issues/254#issuecomment-1777251017) is not correct for `useSyncExternalStore` (it would be correct for an initialiser function for `useState`, though). `useSyncExternalStore` has been designed with server rendering in mind and that's [exactly what `getServerSnapshot` is intended to help with](https://react.dev/reference/react/useSyncExternalStore#adding-support-for-server-rendering) and also why not providing it throws an error if you try to SSR without it. As the docs say, `getServerSnapshot` provides the value used for server rendering and during the hydration pass on the client, so as long as it returns the same value in both environments then there will be no client-server mismatch. If there is no way to determine a sensible initial value on the server, then indeed it's not possible to use with SSR, however `useLocalStorage` has a sensible default value available for use on the server and it should probably be returned instead of throwing an error.

**Comment by silouanwright** [comment]
@gpoole absolutely agree.

```typescript
// Helper to safely access localStorage
const getLocalStorageItem = (key) => {
  if (typeof window === 'undefined') return null;
  try {
    return localStorage.getItem(key);
  } catch (error) {
    console.warn('Unable to access localStorage:', error);
    return null;
  }
};

// Helper to safely set localStorage
const setLocalStorageItem = (key, value) => {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (error) {
    console.warn('Unable to write to localStorage:', error);
  }
};

// Helper to safely remove from localStorage
const removeLocalStorageItem = (key) => {
  if (typeof window === 'undefined') return;
  try {
    localStorage.removeItem(key);
  } catch (error) {
    console.warn('Unable to remove from localStorage:', error);
  }
};

const useLocalStorageSubscribe = (callback) => {
  if (typeof window !== 'undefined') {
    try {
      window.addEventListener("storage", callback);
      return () => window.removeEventListener("storage", callback);
    } catch (error) {
      console.warn('Unable to subscribe to storage events:', error);
    }
  }
  return () => {}; // Noop for SSR or when storage events aren't available
};

// Return the initialValue for server rendering
const getLocalStorageServerSnapshot = (initialValue) => {
  return JSON.stringify(initialValue);
};

export function useLocalStorage(key, initialValue) {
  const getSnapshot = () => getLocalStorageItem(key);

  // We need to capture initialValue in a ref to avoid changing
  // the server snapshot function on re-renders
  const initialValueRef = React.useRef(initialValue);
  
  const store = React.useSyncExternalStore(
    useLocalStorageSubscribe,
    getSnapshot,
    () => getLocalStorageServerSnapshot(initialValueRef.current)
  );

  const setState = React.useCallback(
    (v) => {
      try {
        const prevValue = store ? JSON.parse(store) : initialValueRef.current;
        const nextState = typeof v === "function" ? v(prevValue) : v;

        if (nextState === undefined || nextState === null) {
          removeLocalStorageItem(key);
        } else {
          setLocalStorageItem(key, nextState);
        }
      } catch (e) {
        console.warn('Error updating state:', e);
      }
    },
    [key, store]
  );

  React.useEffect(() => {
    // Only run on the client
    if (
      getLocalStorageItem(key) === null &&
      typeof initialValue !== "undefined"
    ) {
      setLocalStorageItem(key, initialValue);
    }
  }, [key, initialValue]);

  let valueToReturn;
  try {
    valueToReturn = store ? JSON.parse(store) : initialValue;
  } catch (e) {
    console.warn('Error parsing stored value:', e);
    valueToReturn = initialValue;
  }

  return [valueToReturn, setState];
}
```

**Comment by Hosar** [comment]
I switched to **usehooks-ts** it works with no issues.
