### ISSUE TITLE
FR: useEffectOnce() and useUpdateEffect()

### ISSUE THREAD

**Issue by rentalhost** [uidotdev/usehooks#255]
Hello, I wanted to mention some `use` that I find interesting from another library called _usehook-ts_. Technically, both are currently possible, but it's a bit more verbose, so to speak. The suggestions aim to make the process simpler and cleaner.

# useEffectOnce()

- [ ] [`useEffectOnce()`](https://usehooks-ts.com/react-hook/use-effect-once): performs a `useEffect()` only during the first render (mounting). The following implementation is how it could be done today with `usehooks` versus the suggestion:

Using `usehooks`:

```javascript
const firstRender = useIsFirstRender();

useEffect(() => {
  if (firstRender) {
    // do something...
  }
}, []);
```

With the suggestion:

```javascript
useEffectOnce(() => {
  // do something.
});
```

# useUpdateEffect()

- [ ] [`useUpdateEffect()`](https://usehooks-ts.com/react-hook/use-update-effect): this is the opposite of the function above: it only runs from the second render. You can achieve the same using `usehooks` by reversing the `if()` condition.

**Comment by tylermcginnis** [comment]
I debated adding these initially, but decided against it. From a philosophical perspective, I think these go against the mental model for how effects should work in React.
