### ISSUE TITLE
wrong text is copied

### ISSUE THREAD

**Issue by ImLunaHey** [uidotdev/usehooks#256]
The text that's added to the clipboard on https://usehooks.com/usekeypress is not the same as what's shown on the page.

Pretty sure this line is the cause.

https://github.com/uidotdev/usehooks/blob/fa7f8bf3983cad6358c27e1a0547799b0865a168/usehooks.com/src/components/Install.astro#L14

**Comment by tylermcginnis** [comment]
Did you  mean to link to this page, https://usehooks.com/usecopytoclipboard ?

Also, everything looks fine on that page.

**Comment by ImLunaHey** [comment]
Please reopen this.

<img width="921" alt="Screenshot 2023-11-04 at 8 54 33 am" src="https://github.com/uidotdev/usehooks/assets/105922175/cb19fac9-35f9-40ed-aeae-d404e8b9fb0d">


The copy + paste from that page gives me `npm i @uidotdev/usehooks`. It should give `npm i @uidotdev/usehooks@experimental react@experimental react-dom@experimental`.

**Comment by tylermcginnis** [comment]
Ah! Totally misunderstood you, my bad! Just pushed a [fix for this](https://github.com/uidotdev/usehooks/commit/0f3a2b55444c73ee24cda8ca2a86d06ea171aa7d). Thank you!
