### ISSUE TITLE
🪲 BUG: Can't use the hooks on contextAPI file in NextJs14

### ISSUE THREAD

**Issue by ashrafchowdury** [uidotdev/usehooks#261]
## Description
I've been trying to use the hooks on `contextAPI` file in **NextJS14**, but getting a strange error `(Error: useLocalStorage is a client-only hook)`. I'd tried multiple hooks, but neither is working.

## Bug Preview
![Register tsx - chat-app - Visual Studio Code 11_5_2023 12_05_56 PM](https://github.com/uidotdev/usehooks/assets/87828904/fca9f07a-4cb8-4705-883c-badd72fc0734)

**Comment by ottovw** [comment]
It's not a bug. The solution is described here: https://github.com/uidotdev/usehooks/issues/218#issuecomment-1681205155

Here's a issue, proposing better documentation: https://github.com/uidotdev/usehooks/issues/259
