### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by cmdruid** [uidotdev/usehooks#262]
In the old site, each hook had its source code in full display, which was great.

With this new site, the source code seems to be nowhere to be found. Instead, there is a small demo and a lot of promotional material.

Even the links in the github readme just link back to the website, and do not demonstrate the source for any of the hooks?

How do I lookup the actual source code for the hooks? Why was this made so difficult to find?

**Comment by mosesgameli-mtnn** [comment]
It's in [index.js file](https://github.com/uidotdev/usehooks/blob/main/index.js#L1)

**Comment by mosesgameli** [comment]
It's in [index.js file](https://github.com/uidotdev/usehooks/blob/main/index.js#L1)
