### ISSUE TITLE
jest test arent passing 

### ISSUE THREAD

**Issue by Arunjenson** [uidotdev/usehooks#265]
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.
    
    SyntaxError: Cannot use import statement outside a module

**Comment by nicogreenarry** [comment]
See some more discussion of this in #221
