### ISSUE TITLE
useMediaQuery not working on iPhone 6 with iOS 12.5.7

### ISSUE THREAD

**Issue by reekrd** [uidotdev/usehooks#268]
https://usehooks.com/usemediaquery renders an empty demo and example when viewed on an iPhone 6 Plus running iOS 12.5.7

![IMG-0062](https://github.com/uidotdev/usehooks/assets/402302/efcea29e-ac7e-46af-be03-3473f6ebd731)

Any ideas of why?

**Comment by tylermcginnis** [comment]
That's a limitation with Codesandbox and (unfortunately) not much we can do on our end.
