### ISSUE TITLE
useLocalStorage is a client-only hook error on next.js project

### ISSUE THREAD

**Issue by vinaceos** [uidotdev/usehooks#271]
I'm using useLocalStorage on my component wich is marked as "use client"at the top but I keep receiving the error below

 ⨯ node_modules/@uidotdev/usehooks/index.js (613:8) @ Error
 ⨯ Error: useLocalStorage is a client-only hook
    at useLocalStateReducer (./components/shared/ListasProvider.js:46:108)
    at ListasProvider (./components/shared/ListasProvider.js:81:32)

**Comment by vinaceos** [comment]
ok, im using the component ListasProvider at the wrong place

**Comment by tylermcginnis** [comment]
https://github.com/uidotdev/usehooks/issues/254#issuecomment-1776358241
