### ISSUE TITLE
support tree shaking or split index.js into many useXXX.js

### ISSUE THREAD

**Issue by ThisIsManta** [uidotdev/usehooks#281]
To keep my bundle small, I don't use all the hooks provided by the package, but only `useLocalStorage`.
It would be nice if you make this package tree-shake-able or at least split _index.js_ into many _useXXX.js_ files.

**Comment by tansongyang** [comment]
I just installed this library into a Next.js project, did an import (`import { useMediaQuery } from '@uidotdev/usehooks'`) and only that import was included in the final bundle. So tree shaking is working for me.
