### ISSUE TITLE
Error: useSessionStorage is a client-only hook

### ISSUE THREAD

**Issue by reekrd** [uidotdev/usehooks#284]
I'm importing useSessionStorage into a client component but get the error : useSessionStorage is a client-only hook

This happens during build thus the project can't be built. 

And during development. My requested page gets a 500 error but still renders in the browser and data is set in the session storage.

Minimal reproduction can be found here: [https://github.com/reekrd/min-rep-client-only-hook/](https://github.com/reekrd/min-rep-client-only-hook/)

**Comment by mehamednews** [comment]
same error when using `useLocalStorage`

**Comment by JuventinoLVH** [comment]
This is a duplicate of https://github.com/uidotdev/usehooks/issues/218

As said in https://github.com/uidotdev/usehooks/issues/254#issuecomment-1776358241  'use client' not always run on the client.
