### ISSUE TITLE
useGeolocation watch option

### ISSUE THREAD

**Issue by VolteCoOfficial** [uidotdev/usehooks#322]
Hi! 

I'm using `useGeolocation()` and I see I can pass `enableHighAccuracy` and `timeout` but what about watch?
I want it to update my location as soon as I got a new one.

Thank you very much!

**Comment by sagarpanchal** [comment]
Leaving this here for context  https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition

**Comment by VolteCoOfficial** [comment]
So I must use the native `watchPosition`. Thank you.
