### ISSUE TITLE
license

### ISSUE THREAD

**Issue by sungwoncho** [uidotdev/usehooks#40]
I would like to clarify the licenses for the hook examples on the site. Since this repository is released under MIT, does MIT license apply to each example? (in which case, we will have to preserve MIT license text when we copy the example code)

**Comment by JemarJones** [comment]
Had the same thought. To be safe i'll just copy over the licence.

It would be good to clarify this on the site itself, making it clear that someone must include the licence when copying an example

**Comment by gragland** [comment]
I've updated the repo to use unlicense, so no need to copy over a license now.

**Comment by JemarJones** [comment]
Thanks Gabe!
