### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by smithaitufe** [uidotdev/usehooks#48]
I was faced with onClickoutside issue in my component.

I was using [react-onclickoutside](https://github.com/Pomax/react-onclickoutside) package prior to now.

I notice two strange issues.

First, when I have two instances of the same component in the same page, onclickoutside does not work properly.
Secondly, it does not work on when the component was nested in another component.

I researched and found the [useOnClickOutside hook](https://usehooks.com/useOnClickOutside/).
After applying the hook, alll the issues above disappeared.

Thanks

**Comment by gragland** [comment]
Glad the recipe fixed your problems!
