### ISSUE TITLE
Repo conversion to TypeScript

### ISSUE THREAD

**Issue by trblackw** [uidotdev/usehooks#53]
Hey man, looks like you have your hands full with all these issues. Just wanted to reach out a hand of support for any pending issues as well as convey a willingness to convert the repo TypeScript. Since we last worked together I've got a little bit more Gatsby experience under my belt so I feel as though a TS conversion would be a fairly straightforward endeavor. Let me know what you think.

**Comment by gragland** [comment]
Sorry for the late reply. Really appreciate the offer to help. I'm not sure about converting the repo code to TS, but I am interested in adding TS versions of each of the recipes. @bozheville recently added a way to toggle between JS/TS (see https://github.com/gragland/usehooks/pull/89) so we can start adding TS versions.

**Comment by trblackw** [comment]
@gragland No worries on the delay. Piece meal adding TS versions to hooks sounds like a good plan. @bozheville Would you like some help with this? Would be happy to submit PRs for your review. No worries if not, don't want to step on your toes.

**Comment by bozheville** [comment]
@trblackw, it would be perfect. Together we will cover hooks much faster.

@gragland should we open issues before starting working on TS hooks? I see two ways: create a milestone issue and create multiple tasks for hooks (not necessarily hook-per-issue, but like five hooks-per-issue). Or we can create one single issue and put a table inside a description with columns `hook`, `status`, `assignee`. I prefer the second way as it is less complex

**Comment by gragland** [comment]
@bozheville The second way sounds great to me!

**Comment by bozheville** [comment]
@gragland , @trblackw 

I opened an issue #91
