### ISSUE TITLE
How to hook window.onload?

### ISSUE THREAD

**Issue by forconz** [uidotdev/usehooks#55]
```
window.addEventListener('load', handleResize)

    return () => {
      window.removeEventListener('load', handleResize)
    };
```

the code above do not run in useLayoutEffect or useEffect

How to hook window.onload?

**Comment by gragland** [comment]
Can you share the full code here or link to the hook example this is from?

**Comment by iamaamir** [comment]
i dont think you need onload when you are working with React, make use of life cycle functions or may be pre-rendering will be fine.
