### ISSUE TITLE
Cannot open pull request to gist

### ISSUE THREAD

**Issue by ypresto** [uidotdev/usehooks#57]
I want to open PR to `useLocalStorage()` which fixes parse error with `"undefined"` is stored.
Currently this repository references code of every hooks in gist, where PR cannot open.
I suggest to move the code into this repo, so we can easily track changes and open PR.

Thanks!

**Comment by gragland** [comment]
The code examples are currently stored in the markdown frontmatter, which is less than ideal. I pinned an issue with "help wanted" to move that to the markdown body to make contributing much easier: https://github.com/gragland/usehooks/issues/1
