### ISSUE TITLE
Suggestion - add index to website

### ISSUE THREAD

**Issue by zulhfreelancer** [uidotdev/usehooks#58]
Hi,

I noticed that you have a lot of recipes inside the website. I think it will be great if you could add index/table of contents at the top of the website.

Thank you.

**Comment by gragland** [comment]
@zulhfreelancer Thanks for the suggestion! This is definitely on the todo list, although not sure when I'll have time. Would happily take a pull request :)

**Comment by Bates550** [comment]
@gragland Do you have preferences on where it should go? What it should look like? How it should behave?

Simplest thing I could think of was just to add a page at `https://usehooks.com/index` with an alphabetized list of links.

Maybe something like this?
<img width="930" alt="image" src="https://user-images.githubusercontent.com/2865469/75186875-aef18580-56fd-11ea-82ba-e428ff6ffd2e.png">

I've really enjoyed this collection so far and am interested in working on a PR, but wanted to see what y'all were thinking.
