### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by jerrygreen** [uidotdev/usehooks#64]
These hooks look cool, but did you consider publishing them to npm as libraries? So it will be possible to update dependencies, instead of having a constant copy inside our own repo?

> P.S. The only important note here I'd like to mention, - to make possible to use these type of imports:
> 
> `import useAuth from 'usehooks/useAuth'`
> 
> Rather than:
> 
> `import { useAuth } from 'usehooks'`
> 
> Afaik, tools like [NextJS](http://nextjs.org) optimize their buindles based on `from` values (well, it's not just NextJS, it's specific configuration for Webpack). I.e. by describing:
> 
> `from 'usehooks/useAuth'`
> 
> It will bundle only this `useAuth` part and its dependencies, rather than whole `usehooks` library.

> P.P.S. [npmjs.com/usehooks](https://www.npmjs.com/usehooks) is free for now btw

**Comment by gragland** [comment]
Main reason I haven't is that these are meant to be a good starting point for writing your own custom hooks, often requiring some tweaking depending on the use-case, and I don't have a lot of time these days to manage issues / pull-requests. Will think on it in the future if it looks like I have the time.
