### ISSUE TITLE
Minor typo: const App(){

### ISSUE THREAD

**Issue by tjcrowder** [uidotdev/usehooks#7]
Minor typo in first codeblock (the `useLockBodyScroll` example):

```js
const App(){
```

`const` should be `function`:

```js
function App(){
```

(it's right in CodeSandBox.) (Or of course, `const App = () => {`, but it's `function` in CodeSandBox, so best to be consistent.)

**Comment by tjcrowder** [comment]
Heh, I went to fork and fix, and see that the relevant file's been fixed "43 seconds ago" :-)

**Comment by gragland** [comment]
@tjcrowder haha yes just pushed the update. Good catch!
