### ISSUE TITLE
Suggestion: useObjectState

### ISSUE THREAD

**Issue by tsdmrfth** [uidotdev/usehooks#74]
If i have more than one state value i prefer to retrieve them from an object.  Let me explain myself in code.
```
const [email, setEmail] = useState('')
const [password, setPassword] = useState('')
```

So instead adding new useState calls i do like:
`const [{email, password}, setState] = useState({email: '', password:''})`
But  the problem with this is that every time when i want to update one of email or password i should also set previousState. I think  I could not gave the idea. Here is the code:

`onChangeText={text => setState(prevState => ({ ...prevState, email: text }))}`
or again for password
`onChangeText={text => setState(prevState => ({ ...prevState, password: text }))}`

As you can see i need to write `...prevState`

That's why i write useObjectState to fix this.

```
import { useState } from 'react'

export default (initialState) => {
    const [state, setState] = useState(initialState)
    return [state, state => setState(prevState => ({ ...prevState, ...state }))]
}
```

`const [{email, password}, setState] = useObjectState({ email: '', password: '' })`
`onChangeText={text => setState({ password: text })}`

**Comment by gragland** [comment]
Thanks for sharing! This is a useful hook. I'm going to post a recipe for this soon, although probably going to implement with useReducer as someone shared in https://github.com/gragland/usehooks/issues/8
