### ISSUE TITLE
Release as library?

### ISSUE THREAD

**Issue by johnhaynes** [uidotdev/usehooks#86]
I think a lot of users could potentially find it valuable to have access to all these hooks in one library. This would allow people to try everything out in their apps with one NPM package.

It would also allow users to get the latest updates, deprecations, etc instead of baking in copied code that could go out of date.

I think lots of users may find it useful. I know some will want to keep bringing in only individual hooks, so the site will be fine.

Of course there are a lot of other libraries, but it's kind of funny: you're the 4th result
![image](https://user-images.githubusercontent.com/45520429/88213938-5c25e680-cc27-11ea-8d16-75d64675f25e.png)

Just a thought to consider!

**Comment by gragland** [comment]
Hey, thanks for the thought! That's funny that the site is #4 for "react-hook library". It's tempting but I'm not sure I have the time to manage an open source library, which requires a lot more consideration, handling of edge-cases, etc. Nice thing about these examples is they can be extended as needed and the comments often include different variations and improvements. Will certainly consider for the future though if it looks like I have the time. Cheers!
