### ISSUE TITLE
useMedia Bug

### ISSUE THREAD

**Issue by sasweb** [uidotdev/usehooks#9]
After changing a route (e.g. from '/' to '/items') the following error is thrown:

`TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.`

I'm using **CRA 2** and **react-router.**

**Comment by gragland** [comment]
Whoops I left out the first argument for remove `removeEventListener`. It should be `window.removeEventListener('resize', handler)` instead. This is now fixed in the code example.
