### ISSUE TITLE
useInfiniteScroll

### ISSUE THREAD

**Issue by netanel-haber** [uidotdev/usehooks#90]
A Component and a hook used in tandem - to provide infinite scrolling capabilities. Top level of git has both files, example folder is a cra simple usage of the hooks. Sandbox uses that as its' source.

https://github.com/netanel-haber/useInfiniteScroll
https://codesandbox.io/s/damp-mountain-78wnx

**Comment by gragland** [comment]
Thanks for sharing! I really like this hook, although it's a bit too long for the format of usehooks currently. That's more of an issue with usehooks not being setup to be able to truncate posts and have multiple code blocks. Will revisit this in the future when I can accommodate longer posts.
