### ISSUE TITLE
Duplicate all the hooks with TypeScript versions

### ISSUE THREAD

**Issue by bozheville** [uidotdev/usehooks#91]
Status | Hook | Assignee | PR
-- | -- | -- | --
free to take | useFirestoreQuery | - |
free to take | useMemoCompare | - | 
done | useAsync | - | #89
free to take | useRequireAuth | - |
free to take | useRouter | - |
free to take | useAuth | - |
free to take | useEventListener | - |
free to take | useWhyDidYouUpdate | - |
done | useDarkMode | -  | #92 
done | useMedia | - | #92 
done | useLockBodyScroll | - | #105
done | useTheme | - | #105
free to take | useSpring | - | 
free to take | useHistory | - | 
free to take | useScript | - | 
done | useKeyPress | - |  #104
free to take | useMemo | - | 
done | useDebounce | - | #105
done | useOnScreen | - | #105
done | usePrevious | - | #101 | 
taken | useOnClickOutside | @frozenghozt | 
free to take | useAnimation | - | 
done | useWindowSize | - |  #101
done | useHover | - | #105
done | useLocalStorage | - | #92 
done | useToggle | - | #105

workflow:
 1. Anyone can take a hook with `free to take` status
 1. Once a developer wants to convert a hook,  `taken` status and a proper `assignee` appears at a hook
 1. After opening a PR, `pending` status appears as well as PR link in the last column
 1. When a change merged, hook's status becomes `done`, assignee - `-`, PR link remains

:warning: NOTE: Changing statuses, assignee and PR link under a developer responsibility

**Comment by larsroettig** [comment]
@gragland `useWindowSize` i would like to take

**Comment by sanjmgr** [comment]
I would love to see the complete version of all the hooks in the typescript version.

**Comment by diogosilva95** [comment]
I can take useOnClickOutside

**Comment by sanjmgr** [comment]
What do you guys prefer, generic or just interface/type :+1: ?

**Comment by gragland** [comment]
> What do you guys prefer, generic or just interface/type 👍 ?

@bozheville thoughts on this?

**Comment by bozheville** [comment]
I would say that generic with a default type is perfect when possible.

**Comment by nikasepiskveradze** [comment]
usePrevious and useWindowSize hooks are already done(by me) and merged . Who is responsible for updating the status?

**Comment by bozheville** [comment]
@nikasepiskveradze I updated a table

**Comment by nikasepiskveradze** [comment]
@bozheville Could you update the table. I converted those hooks: useHover, useLockBodyScroll, useTheme, useDebounce, useOnScreen and also added new hook useToggle with Typescript version. All of them are already done and merged.

**Comment by bozheville** [comment]
Thank you @nikasepiskveradze! I updated the table

**Comment by GabrielModog** [comment]
I like to pick up useAnimation

**Comment by nsdonato** [comment]
Hi, I would love to contribute, is the table up to date? Thank you <3
